import { TrackId } from './types';

export interface TrackVisualTheme {
  trackId: TrackId;
  name: string;
  enTag: string;
  numStr: string;
  badgePill: string;
  colorName: string;
  borderLeft: string;
  headerHeroBg: string;
  headerBorder: string;
  cardBg: string;
  cardBorder: string;
  iconBg: string;
  iconColor: string;
  tagBadge: string;
  leadBadge: string;
  buttonIdle: string;
  buttonActive: string;
  cardActiveBorder: string;
  cardActiveRing: string;
  conclusionBorder: string;
  conclusionBg: string;
  conclusionText: string;
}

export const TRACK_THEMES: Record<TrackId, TrackVisualTheme> = {
  us_macro: {
    trackId: 'us_macro',
    name: '美股与美元宏观',
    enTag: 'US MACRO & FED',
    numStr: '01',
    badgePill: '美股宏观',
    colorName: 'blue',
    borderLeft: 'border-l-blue-600',
    headerHeroBg: 'bg-gradient-to-r from-slate-950 via-blue-950 to-slate-900',
    headerBorder: 'border-blue-700/60',
    cardBg: 'bg-gradient-to-br from-blue-50/70 via-white to-white',
    cardBorder: 'border-blue-200/80',
    iconBg: 'bg-blue-600 text-white shadow-md shadow-blue-500/30',
    iconColor: 'text-blue-600',
    tagBadge: 'bg-blue-100 text-blue-950 border-blue-300 font-black',
    leadBadge: 'bg-blue-600 text-white shadow-md shadow-blue-500/20',
    buttonIdle: 'bg-blue-50 hover:bg-blue-100 text-blue-900 border-blue-300',
    buttonActive: 'bg-blue-600 text-white border-blue-600 shadow-sm',
    cardActiveBorder: 'border-blue-600',
    cardActiveRing: 'ring-blue-500/20',
    conclusionBorder: 'border-blue-500',
    conclusionBg: 'bg-blue-50/80',
    conclusionText: 'text-blue-950',
  },
  apac_tech: {
    trackId: 'apac_tech',
    name: '算力硬件与前沿模型',
    enTag: 'AI SEMI & LLM MODELS',
    numStr: '02',
    badgePill: '算力与模型',
    colorName: 'emerald',
    borderLeft: 'border-l-emerald-600',
    headerHeroBg: 'bg-gradient-to-r from-slate-950 via-emerald-950 to-slate-900',
    headerBorder: 'border-emerald-700/60',
    cardBg: 'bg-gradient-to-br from-emerald-50/70 via-white to-white',
    cardBorder: 'border-emerald-200/80',
    iconBg: 'bg-emerald-600 text-white shadow-md shadow-emerald-500/30',
    iconColor: 'text-emerald-600',
    tagBadge: 'bg-emerald-100 text-emerald-950 border-emerald-300 font-black',
    leadBadge: 'bg-emerald-600 text-white shadow-md shadow-emerald-500/20',
    buttonIdle: 'bg-emerald-50 hover:bg-emerald-100 text-emerald-900 border-emerald-300',
    buttonActive: 'bg-emerald-600 text-white border-emerald-600 shadow-sm',
    cardActiveBorder: 'border-emerald-600',
    cardActiveRing: 'ring-emerald-500/20',
    conclusionBorder: 'border-emerald-500',
    conclusionBg: 'bg-emerald-50/80',
    conclusionText: 'text-emerald-950',
  },
  commodities_shipping: {
    trackId: 'commodities_shipping',
    name: '大宗商品与能源航运',
    enTag: 'COMMODITIES & SHIPPING',
    numStr: '03',
    badgePill: '大宗航运',
    colorName: 'cyan',
    borderLeft: 'border-l-cyan-600',
    headerHeroBg: 'bg-gradient-to-r from-slate-950 via-cyan-950 to-slate-900',
    headerBorder: 'border-cyan-700/60',
    cardBg: 'bg-gradient-to-br from-cyan-50/70 via-white to-white',
    cardBorder: 'border-cyan-200/80',
    iconBg: 'bg-cyan-600 text-white shadow-md shadow-cyan-500/30',
    iconColor: 'text-cyan-600',
    tagBadge: 'bg-cyan-100 text-cyan-950 border-cyan-300 font-black',
    leadBadge: 'bg-cyan-600 text-white shadow-md shadow-cyan-500/20',
    buttonIdle: 'bg-cyan-50 hover:bg-cyan-100 text-cyan-900 border-cyan-300',
    buttonActive: 'bg-cyan-600 text-white border-cyan-600 shadow-sm',
    cardActiveBorder: 'border-cyan-600',
    cardActiveRing: 'ring-cyan-500/20',
    conclusionBorder: 'border-cyan-500',
    conclusionBg: 'bg-cyan-50/80',
    conclusionText: 'text-cyan-950',
  },
  war_conflict: {
    trackId: 'war_conflict',
    name: '俄乌局势与美伊中东战局',
    enTag: 'WAR & DEFENSE',
    numStr: '03',
    badgePill: '战局防务',
    colorName: 'rose',
    borderLeft: 'border-l-rose-600',
    headerHeroBg: 'bg-gradient-to-r from-slate-950 via-rose-950 to-slate-900',
    headerBorder: 'border-rose-700/60',
    cardBg: 'bg-gradient-to-br from-rose-50/70 via-white to-white',
    cardBorder: 'border-rose-200/80',
    iconBg: 'bg-rose-600 text-white shadow-md shadow-rose-500/30',
    iconColor: 'text-rose-600',
    tagBadge: 'bg-rose-100 text-rose-950 border-rose-300 font-black',
    leadBadge: 'bg-rose-600 text-white shadow-md shadow-rose-500/20',
    buttonIdle: 'bg-rose-50 hover:bg-rose-100 text-rose-900 border-rose-300',
    buttonActive: 'bg-rose-600 text-white border-rose-600 shadow-sm',
    cardActiveBorder: 'border-rose-600',
    cardActiveRing: 'ring-rose-500/20',
    conclusionBorder: 'border-rose-500',
    conclusionBg: 'bg-rose-50/80',
    conclusionText: 'text-rose-950',
  },
  china_domestic: {
    trackId: 'china_domestic',
    name: '中国国内要闻与社会治理',
    enTag: 'CHINA DOMESTIC',
    numStr: '04',
    badgePill: '国内要闻',
    colorName: 'amber',
    borderLeft: 'border-l-amber-500',
    headerHeroBg: 'bg-gradient-to-r from-slate-950 via-amber-950 to-slate-900',
    headerBorder: 'border-amber-700/60',
    cardBg: 'bg-gradient-to-br from-amber-50/70 via-white to-white',
    cardBorder: 'border-amber-200/80',
    iconBg: 'bg-amber-600 text-white shadow-md shadow-amber-500/30',
    iconColor: 'text-amber-600',
    tagBadge: 'bg-amber-100 text-amber-950 border-amber-300 font-black',
    leadBadge: 'bg-amber-600 text-white shadow-md shadow-amber-500/20',
    buttonIdle: 'bg-amber-50 hover:bg-amber-100 text-amber-950 border-amber-300',
    buttonActive: 'bg-amber-600 text-white border-amber-600 shadow-sm',
    cardActiveBorder: 'border-amber-500',
    cardActiveRing: 'ring-amber-500/20',
    conclusionBorder: 'border-amber-500',
    conclusionBg: 'bg-amber-50/80',
    conclusionText: 'text-amber-950',
  },
  china_policy: {
    trackId: 'china_policy',
    name: '发达国家对华举措与博弈',
    enTag: 'GLOBAL DIPLOMACY',
    numStr: '05',
    badgePill: '涉华博弈',
    colorName: 'indigo',
    borderLeft: 'border-l-indigo-600',
    headerHeroBg: 'bg-gradient-to-r from-slate-950 via-indigo-950 to-slate-900',
    headerBorder: 'border-indigo-700/60',
    cardBg: 'bg-gradient-to-br from-indigo-50/70 via-white to-white',
    cardBorder: 'border-indigo-200/80',
    iconBg: 'bg-indigo-600 text-white shadow-md shadow-indigo-500/30',
    iconColor: 'text-indigo-600',
    tagBadge: 'bg-indigo-100 text-indigo-950 border-indigo-300 font-black',
    leadBadge: 'bg-indigo-600 text-white shadow-md shadow-indigo-500/20',
    buttonIdle: 'bg-indigo-50 hover:bg-indigo-100 text-indigo-900 border-indigo-300',
    buttonActive: 'bg-indigo-600 text-white border-indigo-600 shadow-sm',
    cardActiveBorder: 'border-indigo-600',
    cardActiveRing: 'ring-indigo-500/20',
    conclusionBorder: 'border-indigo-500',
    conclusionBg: 'bg-indigo-50/80',
    conclusionText: 'text-indigo-950',
  },
  global_cognition: {
    trackId: 'global_cognition',
    name: '全球宏观认知与深度要闻',
    enTag: 'THINK TANK INTEL',
    numStr: '06',
    badgePill: '全球战略',
    colorName: 'purple',
    borderLeft: 'border-l-purple-600',
    headerHeroBg: 'bg-gradient-to-r from-slate-950 via-purple-950 to-slate-900',
    headerBorder: 'border-purple-700/60',
    cardBg: 'bg-gradient-to-br from-purple-50/70 via-white to-white',
    cardBorder: 'border-purple-200/80',
    iconBg: 'bg-purple-600 text-white shadow-md shadow-purple-500/30',
    iconColor: 'text-purple-600',
    tagBadge: 'bg-purple-100 text-purple-950 border-purple-300 font-black',
    leadBadge: 'bg-purple-600 text-white shadow-md shadow-purple-500/20',
    buttonIdle: 'bg-purple-50 hover:bg-purple-100 text-purple-900 border-purple-300',
    buttonActive: 'bg-purple-600 text-white border-purple-600 shadow-sm',
    cardActiveBorder: 'border-purple-600',
    cardActiveRing: 'ring-purple-500/20',
    conclusionBorder: 'border-purple-500',
    conclusionBg: 'bg-purple-50/80',
    conclusionText: 'text-purple-950',
  },
};
